name: HSharpVE CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install conan
        uses: conan-io/setup-conan@v1

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: |
          conan profile detect
          conan install . --build=missing
          cmake --preset conan-release
          cmake --build build/Release --target tests -j$(nproc)

      - name: Test
        run: ctest build/Release

